// Visual/UI smoke test against an isolated local Next server, using synthetic data.
import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const base=process.env.PRELIM_TEST_URL||'http://127.0.0.1:3127';
if(!['localhost','127.0.0.1'].includes(new URL(base).hostname)) throw new Error('Use a local test server only.');
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
try{
 const page=await browser.newPage({viewport:{width:1372,height:727},deviceScaleFactor:1});
 await page.context().addCookies([{name:'auth-token',value:'visual-test',url:base}]);
 const r={id:1,reference_id:1,version:1,status:'draft',created_by:'Demo import',updated_at:new Date().toISOString(),approved_by:null,approved_at:null,source_text:'SYNTHETIC DEMO: Property taxes. Tax Identification No.: [APN] Fiscal Year: [YEAR] 1st Installment: [AMOUNT / STATUS] 2nd Installment: [AMOUNT / STATUS]',content:{code:'DEMO-01',title:'Property taxes — presentation example',topic:'Taxes / Assessments',matterType:'Exception',scenario:'A reference example for presenting the tax information returned for a property.',guidance:'Keep both installments visible. A reviewer must confirm the wording and applicability before publishing this reference.',documents:'Reviewer to specify applicable source documents.',steps:'1. Check the cited source.\n2. Confirm amounts and status.\n3. Review the wording and presentation.',wording:'SYNTHETIC DEMO — NOT APPROVED\n\nProperty taxes:\n\nTax Identification No.: [APN]\nFiscal Year: [YEAR]\n\n1st Installment: [AMOUNT / STATUS]\n2nd Installment: [AMOUNT / STATUS]',formatNotes:'Bold the field labels. Keep each amount beside its status. Separate the identification fields from the installments with a blank line.',source:'Synthetic demonstration; not a client report or approved title instruction.',boldPhrases:['Tax Identification No.:','Fiscal Year:','1st Installment:','2nd Installment:']}};

 const source={...r,status:'source_approved',approved_by:'Synthetic source approval',approved_at:new Date().toISOString(),content:{...r.content,scenario:'',guidance:'',documents:'',steps:'',matterType:'Unclassified',formatNotes:'DRAFT: formatting requires review.'}};
 const deed={...source,id:2,reference_id:2,content:{...source.content,code:'D1',title:'D1 — Deed of trust',wording:'A deed of trust to secure an indebtedness.\nAmount: $_AMOUNT_\nDated: _DATE_',boldPhrases:[]}};
 const draft={...r,id:3,reference_id:3};
 let reader=false;
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/api/**',async route=>{
  const url=new URL(route.request().url());let data={};
  if(url.pathname==='/api/auth/me')data={user:{id:1,name:'Demo reviewer',email:'demo@example.invalid',role:reader?'viewer':'admin',department:'Title'}};
  if(url.pathname==='/api/workspaces')data={workspaces:[]};
  if(url.pathname==='/api/prelim-references')data={revisions:reader?[source,deed]:[source,deed,draft],canEdit:!reader,canApprove:!reader};
  await route.fulfill({json:data});
 });
 await page.goto(base+'/prelim-standards',{waitUntil:'networkidle',timeout:120000});
 const input=page.getByRole('combobox',{name:'Search references'});
 assert.ok((await input.boundingBox()).y<300,'Search must start above the fold.');
 await page.getByRole('button',{name:'How should property taxes be shown?'}).click();
 await page.getByRole('button',{name:'Copy source wording',exact:true}).waitFor();
 const wording=page.getByRole('article',{name:'Report wording'});
 assert.ok((await wording.boundingBox()).y<500,'Wording must appear near the top, not three screens down.');
 assert.equal(await page.getByText(/unapproved matches/).count(),0);
 assert.equal(await page.getByText('Not yet specified.',{exact:true}).count(),0);
 assert.equal(await page.getByRole('button',{name:'How should property taxes be shown?'}).count(),0);
 assert.equal(await wording.locator('strong').count(),4);
 assert.equal(await page.getByText('Guidance & formatting — not yet reviewed',{exact:true}).isVisible(),true);
 if(process.env.PRELIM_SCREENSHOT)await page.screenshot({path:process.env.PRELIM_SCREENSHOT,fullPage:false,animations:'disabled'});
 await page.context().grantPermissions(['clipboard-read','clipboard-write']);
 await page.getByRole('button',{name:'Copy source wording',exact:true}).click();
 assert.equal((await page.evaluate(()=>navigator.clipboard.readText())).replace(/\r\n/g,'\n'),source.content.wording);
 await page.getByRole('button',{name:'Drafts (1)',exact:true}).click();
 assert.equal(await page.getByRole('button',{name:'Copy source wording',exact:true}).count(),0);
 await page.getByText('Review tools & history',{exact:true}).click();
 await page.getByRole('button',{name:'Edit draft',exact:true}).click();
 await page.getByRole('heading',{name:'Live formatting preview — draft'}).waitFor();
 page.once('dialog',d=>d.dismiss());
 await page.getByRole('button',{name:'Published (1)',exact:true}).click();
 await page.getByRole('button',{name:'Save draft',exact:true}).waitFor();
 await page.getByRole('button',{name:'Cancel',exact:true}).click();
 await page.getByRole('button',{name:'Published (1)',exact:true}).click();
 await input.fill('deed');
 await input.press('ArrowDown');await input.press('Enter');
 await page.getByRole('heading',{name:'D1 — Deed of trust',exact:true}).waitFor();
 assert.ok((await wording.innerText()).includes('$_AMOUNT_'));
 await input.fill('missing-query');
 await page.getByText('No matching references.',{exact:false}).waitFor();
 assert.equal(await page.getByRole('article',{name:'Report wording'}).count(),0,'Do not show stale wording after zero matches.');
 await page.getByRole('button',{name:'Clear',exact:true}).click();
 await page.getByRole('article',{name:'Report wording'}).waitFor();
 // Regular readers see published references only and no review controls.
 reader=true;await page.reload({waitUntil:'networkidle'});
 assert.equal(await page.getByRole('button',{name:/Drafts \(/}).count(),0);
 assert.equal(await page.getByText('Review tools & history',{exact:true}).count(),0);
 await page.setViewportSize({width:390,height:844});
 await page.getByRole('button',{name:'How do I present a deed of trust?'}).click();
 await page.getByRole('heading',{name:'D1 — Deed of trust',exact:true}).waitFor();
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Mobile must not overflow.');
 const box=await page.locator('#reference-detail').boundingBox();
 assert.ok(box.y>=60&&box.y<400,'Mobile search should bring wording into view.');
 if(process.env.PRELIM_SCREENSHOT)await page.screenshot({path:process.env.PRELIM_SCREENSHOT.replace(/\.png$/,'-mobile.png'),fullPage:false,animations:'disabled'});
 assert.deepEqual(errors,[]);
 console.log('PASS: wording-first desktop/mobile layout, automatic selection, source-only labels, draft controls, unsaved-edit guard, keyboard search, zero-result clearing, and exact clipboard copy.');
}finally{await browser.close();}
